#ifndef OPCODES_H
#define OPCODES_H

/* Opcodes */


#define FLOW 0
#define VALUE 1
#define LOGIC 2
#define MATH  3
#define FLOAT 4

#define BUILDOPCODE(group, number, size) ((group << 7) | (number << 2) | size)

#define HALT BUILDOPCODE(FLOW, 0, 0)
#define AHEAD BUILDOPCODE(FLOW, 1, 1)
#define BACK BUILDOPCODE(FLOW, 2, 1)
#define JUMP BUILDOPCODE(FLOW, 3, 1)
#define JUMPHALF BUILDOPCODE(FLOW, 3, 2)
#define JUMPCONST BUILDOPCODE(FLOW, 3, 3)
#define JUMPZERO BUILDOPCODE(FLOW, 4, 1)
#define JUMPZEROHALF BUILDOPCODE(FLOW, 4, 2)
#define JUMPZEROCONST BUILDOPCODE(FLOW, 4,3)
#define JUMPNOTZERO BUILDOPCODE(FLOW, 5, 1)
#define JUMPNOTZEROHALF BUILDOPCODE(FLOW, 5, 2)
#define JUMPNOTZEROCONST BUILDOPCODE(FLOW, 5, 3)
#define JUMPPOSITIVE BUILDOPCODE(FLOW, 6, 1)
#define JUMPPOSITIVEHALF BUILDOPCODE(FLOW, 6, 2)
#define JUMPPOSITIVECONST BUILDOPCODE(FLOW, 7, 3)
#define JUMPNOTPOSITIVE BUILDOPCODE(FLOW, 8, 1)
#define JUMPNOTPOSITIVEHALF BUILDOPCODE(FLOW, 8, 2)
#define JUMPNOTPOSITIVECONST BUILDOPCODE(FLOW, 8, 3)
#define JUMPNEGATIVE BUILDOPCODE(FLOW, 9, 1)
#define JUMPNEGATIVEHALF BUILDOPCODE(FLOW, 9, 2)
#define JUMPNEGATIVECONST BUILDOPCODE(FLOW, 9, 3)
#define JUMPNOTNEGATIVE BUILDOPCODE(FLOW, 10, 1)
#define JUMPNOTNEGATIVEHALF BUILDOPCODE(FLOW, 10, 2)
#define JUMPNOTNEGATIVECONST BUILDOPCODE(FLOW, 10, 3)
#define CALL BUILDOPCODE(FLOW, 11, 1)
#define CALLHALF BUILDOPCODE(FLOW, 11, 2)
#define CALLCONST BUILDOPCODE(FLOW, 11, 3)

#define LOAD BUILDOPCODE(VALUE, 1, 1)
#define LOADHALF BUILDOPCODE(VALUE, 1, 2)
#define LOADCONST BUILDOPCODE(VALUE, 1, 3)
#define INTTOFLOAT BUILDOPCODE(VALUE, 2, 1)
#define FLOATTOINT BUILDOPCODE(VALUE, 3, 1)
#define SHIFTLEFT BUILDOPCODE(VALUE, 4, 1)
#define SHIFTRIGHT BUILDOPCODE(VALUE, 5, 1)
#define ROTLEFT BUILDOPCODE(VALUE, 6, 1)
#define ROTRIGHT BUILDOPCODE(VALUE, 7, 1)
#define COMPARE BUILDOPCODE(VALUE, 8, 1)
#define LOADBYTE BUILDOPCODE(VALUE, 9, 1)
#define LOADBYTECONST BUILDOPCODE(VALUE, 10, 1)



#define NEGATE BUILDOPCODE(MATH, 0, 1)
#define ADD BUILDOPCODE(MATH, 1, 1)
#define ADDHALF BUILDOPCODE(MATH, 2, 2)
#define ADDCONST BUILDOPCODE(MATH, 3, 3)
#define SUBTRACT BUILDOPCODE(MATH, 4, 1)
#define SUBTRACTHALF BUILDOPCODE(MATH, 4, 2)
#define SUBTRACTOCONST BUILDOPCODE(MATH, 4, 3)
#define MULTIPLY BUILDOPCODE(MATH, 5, 1)
#define MULTIPLYHALF BUILDOPCODE(MATH, 5, 2)
#define MULTIPLYCONST BUILDOPCODE(MATH, 5, 3)
#define DIVIDE BUILDOPCODE(MATH, 6, 1)
#define DIVIDEHALF BUILDOPCODE(MATH, 6, 2)
#define DIVIDECONST BUILDOPCODE(MATH, 6, 3)

#define NEGATEFLOAT BUILDOPCODE(FLOAT, 0, 1)  // works identical to NEGATE!
#define ADDFLOAT BUILDOPCODE(FLOAT, 1, 1)
#define ADDFLOATCONST BUILDOPCODE(FLOAT, 1, 3)
#define SUBTRACTFLOAT BUILDOPCODE(FLOAT, 2, 1)
#define SUBTRACTFLOATCONST BUILDOPCODE(FLOAT, 2, 3)
#define MULTIPLYFLOAT BUILDOPCODE(FLOAT, 4, 1)
#define MULTIPLYFLOATCONST BUILDOPCODE(FLOAT, 4, 3)
#define DIVIDEFLOAT BUILDOPCODE(FLOAT, 5, 1)
#define DIVIDEFLOATCONST BUILDOPCODE(FLOAT, 5, 3)

#define NOT BUILDOPCODE(LOGIC, 0, 1)
#define AND BUILDOPCODE(LOGIC, 1, 1)
#define ANDHALF BUILDOPCODE(LOGIC, 1, 2)
#define ANDCONST BUILDOPCODE(LOGIC, 1, 3)
#define NAND BUILDOPCODE(LOGIC, 2, 1)
#define NANDHALF BUILDOPCODE(LOGIC, 2, 2)
#define NANDCONST BUILDOPCODE(LOGIC, 2, 3)
#define OR BUILDOPCODE(LOGIC, 3, 1)
#define ORHALF BUILDOPCODE(LOGIC, 3, 2)
#define ORCONST BUILDOPCODE(LOGIC, 3, 3)
#define NOR BUILDOPCODE(LOGIC, 4, 1)
#define NORHALF BUILDOPCODE(LOGIC, 4, 2)
#define NORCONST BUILDOPCODE(LOGIC, 4, 3)
#define XOR BUILDOPCODE(LOGIC, 5, 1)
#define XORHALF BUILDOPCODE(LOGIC, 5, 2)
#define XORCONST BUILDOPCODE(LOGIC, 5, 3)
#define XNOR BUILDOPCODE(LOGIC, 6, 1)
#define XNORHALF BUILDOPCODE(LOGIC, 6, 2)
#define XNORCONST BUILDOPCODE(LOGIC, 6, 3)

#endif
