#ifndef OPCODES_H
#define OPCODES_H

/* Opcodes */


#define FLOW 0
#define VALUE 1
#define LOGIC 2
#define MATH  3
#define FLOAT 4

#define BUILDOPCODE(group, number, size) ((group << 7) | (number << 2) | size)
#define GET_SIZE(opcode) opcode & 3;

#define HALT BUILDOPCODE(FLOW, 0, 1)
#define AHEAD BUILDOPCODE(FLOW, 1, 1)
#define BACK BUILDOPCODE(FLOW, 2, 1)
#define JUMP BUILDOPCODE(FLOW, 3, 1)
#define JUMP32 BUILDOPCODE(FLOW, 3, 2)
#define JUMP64 BUILDOPCODE(FLOW, 3, 3)
#define JUMPZERO BUILDOPCODE(FLOW, 4, 1)
#define JUMPZERO32 BUILDOPCODE(FLOW, 4, 2)
#define JUMPZERO64 BUILDOPCODE(FLOW, 4,3)
#define JUMPNOTZERO BUILDOPCODE(FLOW, 5, 1)
#define JUMPNOTZERO32 BUILDOPCODE(FLOW, 5, 2)
#define JUMPNOTZERO64 BUILDOPCODE(FLOW, 5, 3)
#define JUMPPOSITIVE BUILDOPCODE(FLOW, 6, 1)
#define JUMPPOSITIVE32 BUILDOPCODE(FLOW, 6, 2)
#define JUMPPOSITIVE64 BUILDOPCODE(FLOW, 7, 3)
#define JUMPNOTPOSITIVE BUILDOPCODE(FLOW, 8, 1)
#define JUMPNOTPOSITIVE32 BUILDOPCODE(FLOW, 8, 2)
#define JUMPNOTPOSITIVE64 BUILDOPCODE(FLOW, 8, 3)
#define JUMPNEGATIVE BUILDOPCODE(FLOW, 9, 1)
#define JUMPNEGATIVE32 BUILDOPCODE(FLOW, 9, 2)
#define JUMPNEGATIVE64 BUILDOPCODE(FLOW, 9, 3)
#define JUMPNOTNEGATIVE BUILDOPCODE(FLOW, 10, 1)
#define JUMPNOTNEGATIVE32 BUILDOPCODE(FLOW, 10, 2)
#define JUMPNOTNEGATIVE64 BUILDOPCODE(FLOW, 10, 3)
#define CALL BUILDOPCODE(FLOW, 11, 1)
#define CALL32 BUILDOPCODE(FLOW, 11, 2)
#define CALL64 BUILDOPCODE(FLOW, 11, 3)

#define LOAD BUILDOPCODE(VALUE, 1, 1)
#define LOAD32 BUILDOPCODE(VALUE, 1, 2)
#define LOAD64 BUILDOPCODE(VALUE, 1, 3)
#define INTTOFLOAT BUILDOPCODE(VALUE, 2, 1)
#define FLOATTOINT BUILDOPCODE(VALUE, 3, 1)
#define SHIFTLEFT BUILDOPCODE(VALUE, 4, 1)
#define SHIFTRIGHT BUILDOPCODE(VALUE, 5, 1)
#define ROTLEFT BUILDOPCODE(VALUE, 6, 1)
#define ROTRIGHT BUILDOPCODE(VALUE, 7, 1)
#define COMPARE BUILDOPCODE(VALUE, 8, 1)
#define LOADBYTE BUILDOPCODE(VALUE, 9, 1)
#define LOADBYTE64 BUILDOPCODE(VALUE, 10, 1)



#define NEGATE BUILDOPCODE(MATH, 0, 1)
#define ADD BUILDOPCODE(MATH, 1, 1)
#define ADD32 BUILDOPCODE(MATH, 2, 2)
#define ADD64 BUILDOPCODE(MATH, 3, 3)
#define SUBTRACT BUILDOPCODE(MATH, 4, 1)
#define SUBTRACT32 BUILDOPCODE(MATH, 4, 2)
#define SUBTRACT64 BUILDOPCODE(MATH, 4, 3)
#define MULTIPLY BUILDOPCODE(MATH, 5, 1)
#define MULTIPLY32 BUILDOPCODE(MATH, 5, 2)
#define MULTIPLY64 BUILDOPCODE(MATH, 5, 3)
#define DIVIDE BUILDOPCODE(MATH, 6, 1)
#define DIVIDE32 BUILDOPCODE(MATH, 6, 2)
#define DIVIDE64 BUILDOPCODE(MATH, 6, 3)

#define LOADFLOAT BUILDOPCODE(FLOAT, 0, 3)
#define NEGATEFLOAT BUILDOPCODE(FLOAT, 1, 1)  // works identical to NEGATE!
#define ADDFLOAT BUILDOPCODE(FLOAT, 2, 1)
#define ADDFLOAT64 BUILDOPCODE(FLOAT, 2, 3)
#define SUBTRACTFLOAT BUILDOPCODE(FLOAT, 3, 1)
#define SUBTRACTFLOAT64 BUILDOPCODE(FLOAT, 3, 3)
#define MULTIPLYFLOAT BUILDOPCODE(FLOAT, 4, 1)
#define MULTIPLYFLOAT64 BUILDOPCODE(FLOAT, 4, 3)
#define DIVIDEFLOAT BUILDOPCODE(FLOAT, 5, 1)
#define DIVIDEFLOAT64 BUILDOPCODE(FLOAT, 5, 3)

#define NOT BUILDOPCODE(LOGIC, 0, 1)
#define AND BUILDOPCODE(LOGIC, 1, 1)
#define AND32 BUILDOPCODE(LOGIC, 1, 2)
#define AND64 BUILDOPCODE(LOGIC, 1, 3)
#define NAND BUILDOPCODE(LOGIC, 2, 1)
#define NAND32 BUILDOPCODE(LOGIC, 2, 2)
#define NAND64 BUILDOPCODE(LOGIC, 2, 3)
#define OR BUILDOPCODE(LOGIC, 3, 1)
#define OR32 BUILDOPCODE(LOGIC, 3, 2)
#define OR64 BUILDOPCODE(LOGIC, 3, 3)
#define NOR BUILDOPCODE(LOGIC, 4, 1)
#define NOR32 BUILDOPCODE(LOGIC, 4, 2)
#define NOR64 BUILDOPCODE(LOGIC, 4, 3)
#define XOR BUILDOPCODE(LOGIC, 5, 1)
#define XOR32 BUILDOPCODE(LOGIC, 5, 2)
#define XOR64 BUILDOPCODE(LOGIC, 5, 3)
#define XNOR BUILDOPCODE(LOGIC, 6, 1)
#define XNOR32 BUILDOPCODE(LOGIC, 6, 2)
#define XNOR64 BUILDOPCODE(LOGIC, 6, 3)

#endif
